### ISSUE TITLE
GeoJsonContent overrides fillParserOutput which was deprecated in MediaWiki 1.38

### ISSUE THREAD

**Issue by samwilson** [ProfessionalWiki/Maps#709] opened 2022-08-21 01:20 UTC
### Setup

- Maps version: 3310ae98c33eeaee4a5ce2ac615b0810bb31ab05
- MW version: fa8646ca7ba3bb599154f02d1793c8c6c99b0875
- PHP version: 8.1.2

### Issue

Saving a new GeoJSON page results in a deprecation notice on Mediawiki 1.39:

> Deprecated: Maps\GeoJsonPages\GeoJsonContent overrides fillParserOutput which was deprecated in MediaWiki 1.38. [Called from MediaWiki\Content\Renderer\ContentRenderer::getParserOutput in mediawiki/includes/content/Renderer/ContentRenderer.php at line 47] in mediawiki/includes/debug/MWDebug.php on line 381

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

1. Enter GeoJSON into a new GeoJson page.
2. Save that page.
3. Observe the above deprecation notice.

**Comment by JeroenDeDauw** [comment] 2023-01-26 19:16
Duplicate of https://github.com/ProfessionalWiki/Maps/issues/698

**Closed by JeroenDeDauw** 2023-01-26 19:16 UTC
Labels: bug, good first issue
