### ISSUE TITLE
Content model 'GeoJSON' is not registered on this wiki

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/Maps#670] opened 2021-10-12 11:11 UTC
### Setup

- Maps version: 8.0
- MW version: 1.35.3
- PHP version:  7.3
- SMW version (if applicable): 

### Issue

Trying to edit a page in the GeoJson namespace results in the following error

```
MWUnknownContentModelException from line 201 of includes/content/ContentHandlerFactory.php: The content model 'GeoJSON' is not registered on this wiki.
See https://www.mediawiki.org/wiki/Content_handlers to find out which extensions handle this content model.

Backtrace:

#0 includes/content/ContentHandlerFactory.php(266): MediaWiki\Content\ContentHandlerFactory->validateContentHandler(string, NULL)
#1 includes/content/ContentHandlerFactory.php(189): MediaWiki\Content\ContentHandlerFactory->createContentHandlerFromHook(string)
#2 includes/content/ContentHandlerFactory.php(97): MediaWiki\Content\ContentHandlerFactory->createForModelID(string)
#3 includes/EditPage.php(546): MediaWiki\Content\ContentHandlerFactory->getContentHandler(string)
#4 includes/EditPage.php(1187): EditPage->isSupportedContentModel(string)
#5 includes/EditPage.php(689): EditPage->initialiseForm()
#6 includes/actions/EditAction.php(71): EditPage->edit()
#7 includes/MediaWiki.php(527): EditAction->show()
#8 includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#9 /srv/ma01/wiki/www/wiki/includes/MediaWiki.php(940): MediaWiki->performRequest()
#10 includes/MediaWiki.php(543): MediaWiki->main()
#11 index.php(53): MediaWiki->run()
#12 /srindex.php(46): wfIndexMain()
#13 {main}
```

**Comment by JeroenDeDauw** [comment] 2021-10-12 11:54
Is Maps enabled?

**Comment by krabina** [comment] 2021-10-14 16:26
no, this does not help. I deactivated everything (except Auth_remoteuser, Bootstrap, ParserHooks, Validator and of course Maps itself.)

**Comment by JeroenDeDauw** [comment] 2021-10-15 11:58
You can ask on a technical MW support channel why it might be broken on some wikis. Here is the relevant code to link to https://github.com/ProfessionalWiki/Maps/blob/master/extension.json#L32-L52

**Comment by krabina** [comment] 2021-10-15 12:24
Thank you, will do. Can it have to do with MW reporting that the namespace 'GeoJSON' is not defined, while in the wiki it is "GeoJson"?

**Comment by JeroenDeDauw** [comment] 2021-10-15 14:00
Note that the error is 

> The content model 'GeoJSON' is not registered

Which is about a *content model*, not about a *namespace*

**Comment by krabina** [comment] 2021-11-09 22:19
Don't know if I did this correctly, but I thought this should be added here:
https://www.mediawiki.org/w/index.php?title=Content_handlers&type=revision&diff=4901165&oldid=4867179

**Comment by krabina** [comment] 2021-11-09 22:26
According to [this](https://www.mediawiki.org/wiki/Manual:Page_content_models#Registration), should it not be something like 
`"GeoJson": "MediaWiki\\Extension\\Maps\\GeoJsonPages\\GeoJsonContentHandler"`
in https://github.com/ProfessionalWiki/Maps/blob/e36df2e383da16f6c332076329a95637cb6499d4/extension.json#L30

**Comment by JeroenDeDauw** [comment] 2021-11-10 00:05
That is not how namespaces are done in the Maps extension and not the cause of the issue.

**Comment by JeroenDeDauw** [comment] 2021-12-14 14:46
I just looked at this again. For some reason the registration in MapsSetup is needed even though it is already in extension.json. Seems like a core bug. Maps does the same thing as the mw.or docs and example extension. No idea why it is not working for @krabina.

**Comment by krabina** [comment] 2021-12-16 21:50
I was able to reproduce this now. The error shows up as soon as Semantic Cite is present!

**Comment by JeroenDeDauw** [comment] 2021-12-17 00:10
Ok, then closing this as I am pretty sure the issue is with SC and you created a new issue there already.

**Comment by krabina** [comment] 2022-01-14 14:47
I am not so sure, btw. On the wiki where I initially encountered this, I removed SC from composer.local.json, removed the extensions directory and the call in LocalSettings.php  and still the error shows up. So it might be unreladted to SC after all...

**Closed** 2022-02-07 19:13 UTC
Labels: bug

**Comment by JeroenDeDauw** [comment] 2022-02-07 19:36
Turned out to be a capitalization mismatch, the type of thing I am pretty blind to. Guess MediaWiki stopped normalizing the names at some point.

**Comment by krabina** [comment] 2022-02-07 19:38
> Thank you, will do. Can it have to do with MW reporting that the namespace 'GeoJSON' is not defined, while in the wiki it is "GeoJson"?

😄

**Comment by JeroenDeDauw** [comment] 2022-02-07 20:00
That is a difference between the NS name and content model ID, which is fine. There also was a difference between the content model ID on some places.
