### ISSUE TITLE
MWCallbackStream::write($string) must be compatible with Psr\\Http\\Message\\StreamInterface::write(string $string

### ISSUE THREAD

**Issue by thebogdan** [ProfessionalWiki/Maps#740] opened 2023-04-30 21:37 UTC
### Setup

- Linux: Ubuntu 22.04.2 LTS
- Apache2: 2.4.52-1ubuntu4.5
- PHP version: 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18)
- MW version: 1.39.3
- MySQL version: 8.0.32-0ubuntu0.22.04.2
- Maps version: 10.0.0

### Issue

I'm totally new to mediawiki and Maps Extension

This morning I installed mediawiki 1.39.3 on Ubuntu 22.04

I installed Maps extension using the steps below

```bash
sudo apt-get install composer
cd /var/www/html/wiki
composer update
COMPOSER=composer.local.json composer require --no-update mediawiki/maps:~10.0
composer update mediawiki/maps --no-dev -o
```

I modified LocalSettings.php to include;

```php
wfLoadExtension( 'Interwiki' );
#  --> install Maps
wfLoadExtension( 'Maps' );
$egMapsDefaultService = 'leaflet';
$egMapsMapWidth = 500;
# <--
wfLoadExtension( 'Math' );
```

... and confirmed **Special:Version** shows Maps is installed, Version 10.0.0

But when I try to add the example from the installation instructions to a page it fails to save/refresh with Error 500

`{{#display_map:center=Brandenburg Gate, Berlin, Germany}}` 

The error message in _/var/log/apache2/error.log_

```bash
PHP Fatal error:  Declaration of MWCallbackStream::write($string) must be compatible with Psr\\Http\\Message\\StreamInterface::write(string $string): int in /var/www/html/wiki/includes/http/MWCallbackStream.php on line 49, referer: http://192.168.2.100/wiki/index.php/MapTest?action=submit&veswitched=1
```

**Comment by JeroenDeDauw** [comment] 2023-04-30 22:10
Looks like this has nothing to do with Maps

**Comment by thebogdan** [comment] 2023-05-01 14:32
OK thank you for the quick response @JeroenDeDauw!

I believe in the process of installing Maps 10.0.0 (which is the only Extension I installed) running `composer update` updated _some library_ which is causing the issue. I rm'd and re-extracted 1.39.3 and alls OK.

Is there a way to install Maps 10.0.0 on 1.39.3 without composer?

**Comment by JeroenDeDauw** [comment] 2023-05-01 14:36
Installation without Composer is unsupported. You are probably right about the cause. The fix probably is to pin the offending package in MediaWiki's composer.json itself. So this looks like an upstream bug in MediaWiki. Maybe it is already fixed in the latest version.

**Closed by JeroenDeDauw** 2023-05-01 14:36 UTC
Labels: bug

**Comment by chiefy** [comment] 2023-06-10 15:12
I know this isn't a Maps bug, but since it's the only extension install I use that requires `composer` I am hitting this same issue.

**Comment by JeroenDeDauw** [comment] 2023-06-10 15:27
Actually ran into the same issue yesterday with External Content: https://github.com/ProfessionalWiki/ExternalContent/actions/runs/5223430655/jobs/9430279743
